### ISSUE TITLE
Problem with NaN data and the /reduce keyword

### ISSUE THREAD

**Issue by schonfsj** [williamsmj/mpfitexy#1]
I've noticed that trying to use the /reduce keyword in mpfitexy.pro with e_y that includes NaNs causes the program to fail, returning NaN for most of the outputs. I think this can be fixed by simply changing line 204 from:
e_int = mean(e_y_)/10.
to:
e_int = mean(e_y_[ok])/10.

I've made this change in my copy of the function and it now seems to work as I would expect.

It also looks like line 237 of mpfitexy2.pro should be:
e_int = mean([e_y1_[ok1], e_y2_[ok2]])/10.

**Comment by mikepqr** [comment]
Thanks for reporting this! Your fix makes sense. I don't currently have access to IDL to double check I haven't introduced an error, so before I merge/release it, please could you take a look at bb65902 and confirm it's what you meant?

**Comment by schonfsj** [comment]
Yep, that's what I had in mind. Just to be clear, I haven't used/tested the
mpfitexy2 version, but since the codes are so parallel, especially in that
section, it seems like it should work the same way.

On Tue, Jun 28, 2016 at 11:26 AM, Mike Williams notifications@github.com
wrote:

> Thanks for reporting this! Your fix makes sense. I don't currently have
> access to IDL to double check I haven't introduced an error, so before I
> merge/release it, please could you take a look at bb65902
> https://github.com/williamsmj/mpfitexy/commit/bb65902e0b920bba9a9ce841708122d6550cbeb6
> and confirm it's what you meant?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/williamsmj/mpfitexy/issues/1#issuecomment-229120540,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANIgrUYjHQNthNgM8GSkd2yNIqqdpOPXks5qQVk6gaJpZM4I_dMW
> .

## 

-Sam Schonfeld-

**Comment by mikepqr** [comment]
Could you do me a favour and:
- run the two scripts `testmpfitexy.pro` and `testmpfitexy2.pro` before that change (i.e. the master branch)
- run the two scripts after the change (i.e. the nanreduce branch), just to check the results look the same

I want to be sure I haven't introduced a basic syntax error or broken anything trivial.

If you don't know your way around github let me know and I'll post the commands to switch between these branches!

If you can't figure out, I'll have to wait until I next have access to IDL to merge this.

**Comment by schonfsj** [comment]
As you've correctly guessed, git is not my forte, and most of my code
retrieval is achieved through an old fashioned copy and paste. So, I
haven't actually tested out the codes on the master and nanreduce branches.
However, I did run the two test scripts on both versions (before and after
applying the fix manually) and the outputs look identical. I won't be
offended if you hold off on merging the changes into the master branch
until you have a chance to test it yourself.

On Tue, Jun 28, 2016 at 1:47 PM, Mike Williams notifications@github.com
wrote:

> Could you do me a favour and:
> - run the two scripts testmpfitexy.pro and testmpfitexy2.pro before
>   that change (i.e. the master branch)
> - run the two scripts after the change (i.e. the nanreduce branch),
>   just to check the results look the same
> 
> I want to be sure I haven't introduced a basic syntax error or broken
> anything trivial.
> 
> If you don't know your way around github let me know and I'll post the
> commands to switch between these branches!
> 
> If you can't figure out, I'll have to wait until I next have access to IDL
> to merge this.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/williamsmj/mpfitexy/issues/1#issuecomment-229161296,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANIgre4YdfxcyMWzG8qoX0oi2mAcirV5ks5qQXpggaJpZM4I_dMW
> .

## 

-Sam Schonfeld-

**Comment by mikepqr** [comment]
Found IDL running on an old server I have access too and this change doesn't seem to break anything, so I'm going to merge it. Thanks for the report (and fix!)

**Comment by schonfsj** [comment]
Of course. And I'm glad it was such an easy fix. Thanks for keeping me in
the loop!

On Tue, Jun 28, 2016 at 5:50 PM, Mike Williams notifications@github.com
wrote:

> Found IDL running on an old server I have access too and this change
> doesn't seem to break anything, so I'm going to merge it. Thanks for the
> report (and fix!)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/williamsmj/mpfitexy/issues/1#issuecomment-229218120,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANIgrSW9ENZexcbfMhvMNZ8cckUZSwCiks5qQbNWgaJpZM4I_dMW
> .

## 

-Sam Schonfeld-
